### ISSUE TITLE
it doesnt work

### ISSUE THREAD

**Issue by Roki100** [igoogolx/shadowsocks-global#2]
Hello, i like the design of this client however i cant seem to connect with a outline ss server, i get some "test website" error, how can i fix that?

**Comment by igoogolx** [comment]
Currently, the outline ss server is not supported. I'm working on a new version. So this issue will be kept open for any updates of the coming new version.

**Comment by Roki100** [comment]
> Currently, the outline ss server is not supported. I'm working on a new version. So this issue will be kept open for any updates of the coming new version.

Okay, thanks for the answer and i will be waiting for the new version  👀

**Comment by igoogolx** [comment]
Finally, [Lux ](https://github.com/igoogolx/lux) is a completely rewritten version, based on this project. Plz try it.
